# Generated by Django 3.1.1 on 2020-10-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usernames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=255, unique=True)),
                ('fieldid', models.CharField(max_length=1000, unique=True)),
                ('tz', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='activity_periods1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('activity_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods1', to='apptwo.usernames')),
            ],
        ),
    ]
